import './global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { IconBell, IconBrandGithub, IconCloudUpload, IconCloudDownload,IconHelpSquareRounded, IconSettings } from '@tabler/icons-react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} layout-fluid font-sans`} data-bs-theme="dark">
        <header className="select-none title-bar bg-zinc-900 fixed left-0 top-0 w-full z-10 border-b border-zinc-950 text-slate-500">
            <div className='columns-3 m-1 items-center'>
              <div>
                  &nbsp;
              </div>
              <div className='flex items-center justify-center title text-xs pt-1'>
                Timemit Desktop
              </div>
              <div className='flex items-center justify-end'>
                <IconBell className='p-1 mr-1 hover:bg-gray-900 hover:text-slate-200 rounded-sm cursor-pointer' size={24} stroke={2} />
                <IconBrandGithub className='p-1 mr-1 hover:bg-gray-900 hover:text-slate-200 rounded-sm cursor-pointer' size={24} stroke={2} />
                <IconCloudUpload className='p-1 mr-1 hover:bg-gray-900 hover:text-slate-200 rounded-sm cursor-pointer' size={24} stroke={2} />
                <IconCloudDownload className='p-1 mr-1 hover:bg-gray-900 hover:text-slate-200 rounded-sm cursor-pointer' size={24} stroke={2} />
                <IconHelpSquareRounded className='p-1 mr-1 hover:bg-gray-900 hover:text-slate-200 rounded-sm cursor-pointer' size={24} stroke={2} />
                <IconSettings className='p-1 hover:bg-gray-900 hover:text-slate-200 rounded-sm cursor-pointer' size={24} stroke={2} />
              </div>
            </div>
        </header>
        {children}</body>
    </html>
  )
}
