'use client'
import './global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Navbar, NavbarBrand, NavbarContent, NavbarItem, Link, Button, DropdownItem, DropdownTrigger, Dropdown, DropdownMenu} from "@nextui-org/react";
import { IconCircleKey, IconSelector, IconBadgeTm, IconDog, IconCat,IconPaw, IconLink } from '@tabler/icons-react';

import {Providers} from "./providers";

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const icons = {
    chevron: <IconSelector  size={16} />,
    dog: <IconDog   size={30} />,
    cat: <IconCat   size={30} />,
    cat2: <IconPaw  size={30} />,
    flash: <IconCircleKey   size={30} />,
    server: <IconCircleKey  size={30} />,
    user: <IconCircleKey  size={30} />,
  };

  return (
    <html lang="en" className='light'>
      <body className={`${inter.className} layout-fluid font-sans text-foreground bg-background antialiased`} data-bs-theme="dark">
      <Navbar>
        <NavbarBrand>
          <IconBadgeTm />
          <p className="ml-1 font-bold text-inherit">Timemit</p>
        </NavbarBrand>
        <NavbarContent className="hidden sm:flex gap-4" justify="end">
          <NavbarItem>
            <Link color="foreground" href="/rayi" aria-current="page">
              Rayi
            </Link>
          </NavbarItem>
          <Dropdown>
            <NavbarItem>
              <DropdownTrigger>
                <Button
                  disableRipple
                  className="p-0 bg-transparent data-[hover=true]:bg-transparent text-base"
                  endContent={icons.chevron}
                  radius="sm"
                  variant="light"
                >
                  Living
                </Button>
              </DropdownTrigger>
            </NavbarItem>
            <DropdownMenu
              aria-label="ACME features"
              className="w-[340px]"
              itemClasses={{
                base: "gap-4",
              }}
            >
              <DropdownItem
                key="autoscaling"
                description="一只可爱的小柴柴"
                startContent={icons.dog}
              >
                <Link href="/life/danding">
                  但丁
                </Link>
              </DropdownItem>
              <DropdownItem
                key="usage_metrics"
                description="满脸严肃的英短银渐层猫咪."
                startContent={icons.cat}
              >
                <Link href="/life/keguan">
                  客官
                </Link>
              </DropdownItem>
              <DropdownItem
                key="usage_metrics"
                description="可爱但是胆小的黑白色小母猫."
                startContent={icons.cat}
              >
                <Link href="/life/naitang">
                  奶糖
                </Link>
              </DropdownItem>
            </DropdownMenu>
          </Dropdown>
          <NavbarItem>
            <Link color="foreground" href="/photoes">
              Photoes
            </Link>
          </NavbarItem>
          <NavbarItem>
            <Link color="foreground" href="/projects">
              Projects
            </Link>
          </NavbarItem>
        </NavbarContent>
        <NavbarContent justify="end">
          <NavbarItem>
            <Button size="sm" endContent={<IconLink size={16} />} as={Link} color="warning" href="https://fastuse.cloud" target='_blank' variant="flat">
              FastUseCloud
            </Button>
          </NavbarItem>
          <NavbarItem>
            <Button size="sm" endContent={<IconLink size={16} />} as={Link} color="warning" href="https://quanzi.io" target='_blank' variant="flat">
              Quanzi
            </Button>
          </NavbarItem>
        </NavbarContent>
      </Navbar>
        <Providers>
          {children}
        </Providers>
        </body>
    </html>
  )
}
